services:
  php:
    build:
      context: .
    container_name: php
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./var/log:/var/www/html/var/log
    ports:
      - "80:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: